# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vup < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leocavalcante/vup/releases/download/v0.3.0/vup_0.3.0_darwin_amd64.tar.gz"
      sha256 "40fe4f5f1a8db5f0b499b9d4464c0a0cd00f247d89ddef713fdd8fcd7b916b9f"

      def install
        bin.install "vup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leocavalcante/vup/releases/download/v0.3.0/vup_0.3.0_darwin_arm64.tar.gz"
      sha256 "78ea5e8f539272035e55618f5f62ee63d4a369f89483993b2a0f68047b0427f8"

      def install
        bin.install "vup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leocavalcante/vup/releases/download/v0.3.0/vup_0.3.0_linux_amd64.tar.gz"
        sha256 "acef41689433c90eb6d95e938a940a4f7c3d630cf62dbc991835775e43a2f655"

        def install
          bin.install "vup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leocavalcante/vup/releases/download/v0.3.0/vup_0.3.0_linux_arm64.tar.gz"
        sha256 "7e4000655a389a678e76e14b26f0addf5a8598c7bc511d58a7503de8477f0fd1"

        def install
          bin.install "vup"
        end
      end
    end
  end
end
